apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: slack-formatter
  name: slack-formatter
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: slack-formatter:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/locriandev/slack-formatter.git
      ref: main
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/python-311:1-86
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
